### ISSUE TITLE
Adding a single unpositioned node destroys positioning of all others

### ISSUE THREAD

**Issue by SLesslyTall** [peteshadbolt/abp#16]
Adding a single, unpositioned node to a set of already positioned nodes removes any defined positioning and defaults all positions to the inbuilt function.

See below code snippet for an example
```
from abp.fancy import GraphState
import networkx as nx

edges = [(0,1),(1,2),(2,3),(3,4)]
nodes = [(i, {'x': i, 'y': 0, 'z':0}) for i in range(5)]
gs = GraphState()

for node, position in nodes:
    gs.add_qubit(node, position=position)
    gs.act_hadamard(node)

for edge in edges:
    gs.act_cz(*edge)
gs.update(3)
# a single line of qubits are created along the x axis
gs.add_qubit('start')
gs.update(3)
# a curved 5-qubit cluster and single qubit is depicted
```

An ideal positioning function should respect any stated positions and only auto-position any left unpositioned.

**Comment by SLesslyTall** [comment]
Am happy to attempt an implementation myself, but will need some direction on this.

**Comment by peteshadbolt** [comment]
I think that the complexity of a good (rather than lazy) solution to this issue is too high to warrant trying to solve it. Think about it -- you'd need to do something like 

- figure out the bounding box of the nodes that do have `position` attributes
- auto-layout the remaining nodes
- figure out the bounding box of that lump
- intelligently arrange things so that the bounding boxes do not intersect

Ok, this is like 20 lines of code but that's too much complexity imo. Prefer all-or-nothing.

If you really disagree with this, feel free to complain :smile:

**Comment by SLesslyTall** [comment]
Yeah, that's probably fair, but this feature should be included in the docs. It confused me for quite a while!
